//! `APM` — Adaptive Probability Map, port of `template<int S> struct APM`
//! (`fxcmv1.cpp:1622-1643`), translated 1:1 from `apm.rs`.
//!
//! An APM refines an input probability `pr` (12-bit, 0..4095) given a context
//! `cxt` (0..N-1). It keeps, per context, a 33-point piecewise-linear table over
//! the *stretched* probability axis. `p` first nudges the two table points that
//! the previous call interpolated between toward the just-seen bit `y`, then
//! latches the new `(pr, cxt)` and returns the interpolated 16-bit table value
//! shifted back down to a 12-bit probability.
//!
//! Faithfulness notes (vs the C++ / Rust):
//! - `squash`/`stretch` come from `tables.zig` (the C++ used the file-global
//!   `sqt`/`strt` tables). `stretch(pr)` indexes `strt[pr]`, so `pr` **must** be
//!   in `0..=4095`.
//! - `t[i]` is a `u16`; the learning update `t += (g - t) >> rate` is computed in
//!   32-bit signed and stored back truncated to 16 bits — replicated with `i32`
//!   math and a final low-16-bit truncation (matching Rust `as u16`).
//! - `>>` on the signed update and on the final blend is arithmetic (Zig `>>` on a
//!   signed type is arithmetic, matching g++/Rust here).
//! - `w = pr & 127` uses the *stretched* (possibly negative) `pr`; the low-7-bit
//!   mask on a two's-complement value matches between C and Rust.
//! - `index` carries across calls (the table points to refine next time); `new`
//!   seeds it to 0 so the first call refines `t[0]`/`t[1]`.

const std = @import("std");
const Tables = @import("tables.zig").Tables;

pub const Apm = struct {
    /// Index (into `t`) of the lower of the two points the last `p` blended.
    index: usize,
    /// `[N][33]`: stretched-prob bucket -> 16-bit-scaled probability.
    t: []u16,
    /// Number of contexts (`S` in the C++ template).
    n: usize,

    /// `APM<n>::Init`. Seeds every context's 33-point row to
    /// `squash((j-16)*128)*16`.
    pub fn new(a: std.mem.Allocator, tables: *const Tables, n: usize) !Apm {
        std.debug.assert(n >= 1); // APM needs at least one context
        const t = try a.alloc(u16, n * 33);
        @memset(t, 0);
        var j: i32 = 0;
        while (j < 33) : (j += 1) {
            t[@intCast(j)] = @intCast(tables.squash((j - 16) * 128) * 16);
        }
        var i: usize = 33;
        while (i < n * 33) : (i += 1) {
            t[i] = t[i - 33];
        }
        return Apm{ .index = 0, .t = t, .n = n };
    }

    pub fn deinit(self: *Apm, a: std.mem.Allocator) void {
        a.free(self.t);
    }

    /// `APM::p(pr, cxt, rate, y)` — refine `pr` in context `cxt`, learning from `y`.
    ///
    /// `pr` must be in `0..=4095` (it indexes the stretch table). `cxt` must be in
    /// `0..n`. `y` is the bit just observed (0/1). Returns a 12-bit probability.
    pub fn p(self: *Apm, tables: *const Tables, pr_in: i32, cxt: i32, rate: i32, y: i32) i32 {
        std.debug.assert(pr_in >= 0 and pr_in <= 4095);
        std.debug.assert(cxt >= 0 and @as(usize, @intCast(cxt)) < self.n);
        std.debug.assert(y == 0 or y == 1);

        const pr: i32 = @as(i32, tables.stretch(pr_in));
        const g: i32 = (y << 16) + (y << @as(u5, @intCast(rate))) - y * 2;

        // Refine the two points latched by the previous call (or t[0]/t[1] init).
        const lo = self.index;
        const cur0: i32 = @as(i32, self.t[lo]);
        self.t[lo] = @truncate(@as(u32, @bitCast(cur0 + ((g - cur0) >> @as(u5, @intCast(rate))))));
        const cur1: i32 = @as(i32, self.t[lo + 1]);
        self.t[lo + 1] = @truncate(@as(u32, @bitCast(cur1 + ((g - cur1) >> @as(u5, @intCast(rate))))));

        const w: i32 = pr & 127; // interpolation weight (33 points)
        const index: usize = @as(usize, @intCast((pr + 2048) >> 7)) + @as(usize, @intCast(cxt)) * 33;
        self.index = index;

        return (@as(i32, self.t[index]) * (128 - w) + @as(i32, self.t[index + 1]) * w) >> 11;
    }
};

// ---- Golden values from apm_ref.rs (generated by the compiled C++ oracle) ----
const PR_SAMPLES = [_]i32{
    3918, 300,  1532, 478,  587,  1278, 3894, 891,  1926, 3646, 2161, 3695, 3425, 941,  2667, 1200, 1459,
    2255, 979,  1777, 949,  2036, 846,  3482, 2628, 2547, 2548, 2888, 3190, 2391, 3689, 1415, 2845,
    1785, 1324, 1362, 3393, 747,  1714, 2935, 1010, 3677, 1746, 1071, 2483, 2291, 3731, 3340, 1490,
    2844, 309,  3547, 3171, 322,  955,  3193, 1147, 2526, 160,  2121, 2225, 1998, 2198, 1481, 3549,
    2510, 1403, 3881, 84,   2678, 3329, 2004, 3571, 732,  418,  3798, 2716, 3335, 927,  2796, 3718, 1016,
    3415, 3102, 710,  2334, 2855, 3361, 1104, 1600, 3188, 2067, 3602, 1393, 3493, 3691, 358,  677,
    3171, 1233, 2467, 3718, 1046, 915,  1182, 3147, 3943, 1354, 1355, 1359, 2591, 2597, 1243, 3975,
    2135, 1768, 2595, 2563, 2103, 2606, 1849, 2726, 2154, 1780, 1997, 2392,
};
const PR_CS: u64 = 15683788121478948089;
const T_CS: u64 = 13674098568319991653;

fn xs(s: *u32) u32 {
    s.* ^= s.* << 13;
    s.* ^= s.* >> 17;
    s.* ^= s.* << 5;
    return s.*;
}

const RATES = [_]i32{ 3, 6, 7, 8, 9 };

test "matches_cpp_oracle" {
    const a = std.testing.allocator;
    var tables = try Tables.new(a);
    defer tables.deinit(a);

    // Must mirror oracle.cpp's drivecalls exactly: (n, seed, steps).
    const Cfg = struct { n: usize, seed: u32, steps: usize };
    const cfgs = [_]Cfg{
        .{ .n = 256, .seed = 0x0001_2345, .steps = 100_000 },
        .{ .n = 33, .seed = 0x0000_BEEF, .steps = 60_000 },
        .{ .n = 1024, .seed = 0x00AB_CDEF, .steps = 100_000 },
        .{ .n = 2, .seed = 0x0000_CAFE, .steps = 40_000 },
    };

    var pr_cs: u64 = 0;
    var t_cs: u64 = 0;
    var samples = std.ArrayList(i32){};
    defer samples.deinit(a);

    for (cfgs) |cfg| {
        var ap = try Apm.new(a, &tables, cfg.n);
        defer ap.deinit(a);
        var s = cfg.seed;
        var step: usize = 0;
        while (step < cfg.steps) : (step += 1) {
            const v = xs(&s);
            const pr: i32 = @intCast(v & 4095);
            const cxt: i32 = @intCast((v >> 12) % @as(u32, @intCast(cfg.n)));
            const y: i32 = @intCast((v >> 24) & 1);
            const rate = RATES[@intCast((v >> 25) % 5)];
            const out = ap.p(&tables, pr, cxt, rate, y);
            pr_cs = pr_cs *% 1000003 +% @as(u64, @as(u32, @bitCast(out)));
            if (step < 24 or step % 9999 == 0) {
                try samples.append(a, out);
            }
        }
        for (ap.t) |vv| {
            t_cs = t_cs *% 1000003 +% @as(u64, vv);
        }
    }

    try std.testing.expectEqualSlices(i32, PR_SAMPLES[0..], samples.items);
    try std.testing.expectEqual(PR_CS, pr_cs);
    try std.testing.expectEqual(T_CS, t_cs);
}
