//! `StateMap1` — port of `struct StateMap1` (`fxcmv1.cpp:707-736`), translated
//! 1:1 from `state_map1.rs`.
//!
//! A count-limited, learning-rate-decayed StateMap. Each context slot packs a
//! 20-bit prediction in the high bits and a 10-bit hit count in the low bits of a
//! `u32`. `set(c)` first runs `update` against the *previous* context using the
//! latched bit `y`, then latches the new context `c & mask` and returns its
//! 12-bit prediction (`t >> 20`).
//!
//! Faithfulness notes (vs the C++/Rust):
//! - `dt[n]` is the shared decay table (`4096/(n+2)`, `dt[1023]=1`) — threaded in
//!   via `Tables` (the C++ used the file-global `dt`). We keep the `tables`
//!   parameter (typed `anytype`) reading `tables.dt[...]`, so both the real
//!   `tables.zig` `Tables` and the self-contained test struct work; this keeps
//!   the module independently testable while matching the Rust signature shape.
//! - The blend term `((y<<20)-pr1)*dt[n]+512` is computed in 32-bit signed
//!   arithmetic; the product can overflow `i32` at the boundary (e.g. `n==0`,
//!   `pr1==0`, `y==1` gives `2^31`). C++ wraps (2's-complement), so we use
//!   wrapping `*%`/`+%` and `@bitCast` to `u32` before the `& 0xfffffc00` mask,
//!   exactly matching the implicit `int -> unsigned` of the `0xfffffc00` literal.
//! - `>>` on `pr1`/`pr` reads from a `u32`, so the shifts are logical.

const std = @import("std");

pub const StateMap1 = struct {
    /// `cxt -> (prediction << 12) | count`, packed into a `u32`.
    t: []u32,
    /// Context of the last prediction (index into `t`).
    cxt: usize,
    /// Last 12-bit prediction returned by `set`.
    pr: i32,
    /// `n - 1`; ANDs the incoming context into range.
    mask: i32,
    /// Maximum count used for the decay (`1..=1023`).
    limit: i32,

    /// `StateMap1::Init(n, lim)`. `n` must be a power of two; `0 < lim < 1024`.
    pub fn new(allocator: std.mem.Allocator, n: usize, limit: i32) !StateMap1 {
        std.debug.assert(std.math.isPowerOfTwo(n)); // "n must be a power of two"
        std.debug.assert(limit > 0 and limit < 1024); // "limit must be in 1..1024"
        const t = try allocator.alloc(u32, n);
        @memset(t, @as(u32, 1) << 31);
        return StateMap1{
            .t = t,
            .cxt = 0,
            .pr = 2048,
            .mask = @as(i32, @intCast(n)) - 1,
            .limit = limit,
        };
    }

    pub fn deinit(self: *StateMap1, allocator: std.mem.Allocator) void {
        allocator.free(self.t);
        self.t = &[_]u32{};
    }

    /// `StateMap1::update` — blend the latched bit `y` into the current context.
    inline fn update(self: *StateMap1, tables: anytype, y: i32) void {
        std.debug.assert(y == 0 or y == 1);
        const p0 = self.t[self.cxt];
        const n: i32 = @intCast(p0 & 1023); // count
        const pr1: i32 = @intCast(p0 >> 12); // 20-bit prediction
        var np = p0;
        if (n < self.limit) {
            np = np +% 1;
        }
        // ((y<<20)-pr1)*dt[n]+512, 32-bit signed (may wrap), then mask low 10 bits.
        const term_i: i32 = ((y << 20) - pr1) *% tables.dt[@as(usize, @intCast(n))] +% 512;
        const term: u32 = @as(u32, @bitCast(term_i)) & 0xffff_fc00;
        np = np +% term;
        self.t[self.cxt] = np;
    }

    /// `StateMap1::set(c)` — update against the previous context with `y`, latch the
    /// new context `c & mask`, and return its 12-bit prediction.
    pub inline fn set(self: *StateMap1, tables: anytype, y: i32, c: i32) i32 {
        self.update(tables, y);
        self.cxt = @intCast(c & self.mask);
        self.pr = @intCast(self.t[self.cxt] >> 20);
        return self.pr;
    }

    /// Current latched prediction. (Rust name: `pr`; renamed to avoid the
    /// Zig field/decl name collision with field `pr`.)
    pub inline fn get_pr(self: *const StateMap1) i32 {
        return self.pr;
    }
};

// ---- goldens (from state_map1_ref.rs, generated by the C++ oracle) ----

/// Sampled `pr` outputs (`step < 24 || step % 9999 == 0`) across all configs.
const PR_SAMPLES = [_]i32{
    2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048,
    2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2379, 2497, 1970, 2073, 1999, 2027, 2123, 2032,
    1912, 1910, 2048, 2048, 1024, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048,
    2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 1433, 2598, 1868, 1679, 1800, 2192,
    2451, 2048, 1696, 1770, 2048, 2048, 2048, 2048, 3072, 2048, 2048, 3072, 2048, 3072, 2048, 2048,
    3072, 2560, 2048, 2048, 2048, 3072, 2867, 1024, 2048, 2048, 1024, 3413, 2216, 1971, 2695, 1795,
    2021, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048,
    2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 682,  682,  1023, 2662, 1303, 1514, 1617,
    970,  2046, 1450,
};

/// `cs = cs*1000003 + (u32)pr` over every `pr` produced (all configs).
const PR_CS: u64 = 3491727857752600288;

/// `cs = cs*1000003 + t[i]` over the final `t[]` of every config.
const T_CS: u64 = 6316962684870258394;

fn xs(s: *u32) u32 {
    s.* ^= s.* << 13;
    s.* ^= s.* >> 17;
    s.* ^= s.* << 5;
    return s.*;
}

test "matches_cpp_oracle" {
    const allocator = std.testing.allocator;

    // Build the shared decay table dt[i] = 4096/(i+2), dt[1023]=1 (mirrors Tables).
    const Tables = struct { dt: [1024]i32 };
    var tables: Tables = undefined;
    for (0..1024) |i| {
        tables.dt[i] = @divTrunc(4096, @as(i32, @intCast(i)) + 2);
    }
    tables.dt[1023] = 1;

    // Must mirror oracle.cpp's `cfgs` exactly.
    const Cfg = struct { n: usize, lim: i32, seed: u32, steps: usize };
    const cfgs = [_]Cfg{
        .{ .n = 256, .lim = 255, .seed = 0x0001_2345, .steps = 100_000 },
        .{ .n = 1024, .lim = 1023, .seed = 0x0000_BEEF, .steps = 100_000 },
        .{ .n = 16, .lim = 8, .seed = 0x0000_CAFE, .steps = 50_000 },
        .{ .n = 4096, .lim = 511, .seed = 0x00AB_CDEF, .steps = 100_000 },
    };

    var pr_cs: u64 = 0;
    var t_cs: u64 = 0;
    var samples = std.ArrayList(i32){};
    defer samples.deinit(allocator);

    for (cfgs) |cfg| {
        var sm = try StateMap1.new(allocator, cfg.n, cfg.lim);
        defer sm.deinit(allocator);
        var s = cfg.seed;
        var step: usize = 0;
        while (step < cfg.steps) : (step += 1) {
            const v = xs(&s);
            const y: i32 = @intCast(v & 1);
            const c: i32 = @bitCast(v >> 1);
            const pr = sm.set(&tables, y, c);
            pr_cs = pr_cs *% 1000003 +% @as(u64, @as(u32, @bitCast(pr)));
            if (step < 24 or step % 9999 == 0) {
                try samples.append(allocator, pr);
            }
        }
        for (sm.t) |val| {
            t_cs = t_cs *% 1000003 +% @as(u64, val);
        }
    }

    try std.testing.expectEqualSlices(i32, PR_SAMPLES[0..], samples.items);
    try std.testing.expectEqual(PR_CS, pr_cs);
    try std.testing.expectEqual(T_CS, t_cs);
}
